"""Bootstrap a corpus-specific guideline.yaml draft from the committed corpus.

`esdc corpus learn --init-guideline` samples documents, asks the LLM to
propose claim types and per-doc-type hints, validates the proposal, and
writes ~/.esdc/guideline.yaml for the user to review and edit. Entity
types are never generated — they are code-bound (resolver + graph schema).
"""

from __future__ import annotations

import re
import sqlite3
from collections.abc import Callable
from pathlib import Path
from typing import Any

import yaml

from esdc.corpus.metadata import parse_llm_json
from esdc.knowledge.guideline import _DEFAULT_PATH, load_guideline

_SNAKE = re.compile(r"[a-z][a-z0-9_]*")

_HEADER = """\
# Generated by `esdc corpus learn --init-guideline` from your corpus.
# REVIEW BEFORE USE: fix descriptions, prune types you don't want, add
# predicate examples. Then run: esdc corpus learn
# Editing this file re-triggers extraction for all documents.
"""


def sample_documents(
    sqlite_conn: sqlite3.Connection,
    per_type: int = 6,
    excerpt_chars: int = 1500,
) -> list[dict[str, Any]]:
    doc_types = [
        r[0]
        for r in sqlite_conn.execute(
            "SELECT DISTINCT doc_type FROM documents WHERE doc_type IS NOT NULL"
        ).fetchall()
    ]
    samples: list[dict[str, Any]] = []
    for doc_type in sorted(doc_types):
        rows = sqlite_conn.execute(
            "SELECT doc_type, doc_topic, subject, markdown FROM documents "
            "WHERE doc_type = ? ORDER BY doc_date",
            (doc_type,),
        ).fetchall()
        step = max(1, len(rows) // per_type)
        for row in rows[::step][:per_type]:
            samples.append(
                {
                    "doc_type": row["doc_type"],
                    "doc_topic": row["doc_topic"],
                    "subject": row["subject"],
                    "excerpt": (row["markdown"] or "")[:excerpt_chars],
                }
            )
    return samples


def build_bootstrap_prompt(
    samples: list[dict[str, Any]], entity_types: dict[str, str]
) -> str:
    entity_lines = "\n".join(f"- {name}: {desc}" for name, desc in entity_types.items())
    sample_lines = "\n\n".join(
        f"[doc_type={s['doc_type']} topic={s['doc_topic']}] {s['subject']}\n"
        f"{s['excerpt']}"
        for s in samples
    )
    return f"""You design an extraction taxonomy for a corpus of Indonesian
upstream oil & gas documents (approval letters, MoM, regulations —
bilingual Indonesian/English). The taxonomy steers an LLM that extracts
typed claims from each document.

Fixed entity types (do NOT propose new ones):
{entity_lines}

Corpus samples:
{sample_lines}

Return ONLY a JSON object:
{{
  "claim_types": {{
    "<snake_case_name>": "<what qualifies; include 3-6 predicate examples
      with units in the name, e.g. npv_musd, irr_pct, onstream_date>"
  }},
  "doc_type_hints": {{
    "<doc_type occurring in the samples>": "<one sentence: what the
      extractor should focus on for this document type>"
  }}
}}

Rules:
- 5 to 10 claim types, covering what these documents actually contain:
  approvals/decisions, economics, volumes, commitments, issues, schedule.
- Descriptions are extraction instructions, not glossary entries.
- Predicate examples define naming conventions — consistent snake_case
  with units embedded."""


def generate_guideline_yaml(
    sqlite_conn: sqlite3.Connection, llm_caller: Callable[[str], str]
) -> str:
    packaged = load_guideline(_DEFAULT_PATH)
    samples = sample_documents(sqlite_conn)
    seen_doc_types = {s["doc_type"] for s in samples}
    parsed = parse_llm_json(
        llm_caller(build_bootstrap_prompt(samples, packaged.entity_types))
    )

    claim_types: dict[str, str] = {}
    raw_claims = parsed.get("claim_types")
    if isinstance(raw_claims, dict):
        for name, desc in raw_claims.items():
            if (
                isinstance(name, str)
                and _SNAKE.fullmatch(name)
                and isinstance(desc, str)
                and desc.strip()
            ):
                claim_types[name] = desc.strip()
    if not claim_types:
        raise ValueError(
            "LLM proposed no valid claim types; rerun --init-guideline "
            "or write guideline.yaml by hand."
        )

    doc_type_hints: dict[str, str] = {}
    raw_hints = parsed.get("doc_type_hints")
    if isinstance(raw_hints, dict):
        for name, desc in raw_hints.items():
            if name in seen_doc_types and isinstance(desc, str) and desc.strip():
                doc_type_hints[name] = desc.strip()

    data = {
        "version": 1,
        "entity_types": dict(packaged.entity_types),
        "claim_types": claim_types,
        "doc_type_hints": doc_type_hints,
    }
    return _HEADER + yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=78)


def init_guideline(
    *,
    force: bool = False,
    sqlite_conn: sqlite3.Connection | None = None,
    llm_caller: Callable[[str], str] | None = None,
) -> Path:
    from esdc.configs import Config

    target = Config.get_db_dir() / "guideline.yaml"
    if target.exists() and not force:
        raise FileExistsError(
            f"{target} already exists. Use --force to regenerate "
            f"(your edits will be lost)."
        )

    close_sqlite = False
    if sqlite_conn is None:
        from esdc.pod_registry.store import get_sqlite_connection

        sqlite_conn = get_sqlite_connection()
        close_sqlite = True
    try:
        if llm_caller is None:
            from esdc.knowledge.learn import _open_default_llm

            llm_caller, _, _ = _open_default_llm()
        text = generate_guideline_yaml(sqlite_conn, llm_caller)
    finally:
        if close_sqlite:
            sqlite_conn.close()

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    return target
