[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "esdc"
version = "0.1.0"
description = "A package for retrieving and managing eSDC data."
authors = [
  { name = "Fajril Ambia", email = "fajril@ambia.id" },
]
license = { file = "LICENSE" }
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/fajril/esdc"

[tool.setuptools]
packages = ["esdc"]

[tool.setuptools.package-data]
esdc = ["data/*"]

[tool.setuptools.exclude-package-data]
esdc = ["tests"]
