[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "esdc"
version = "0.2.1"
description = "A package for retrieving and managing eSDC data."
authors = [
  { name = "Fajril Ambia", email = "fajril@ambia.id" },
]
license = { file = "LICENSE" }
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
]
dependencies = [
  "requests==2.32.2",
  "python-dotenv==1.0.1",
  "pandas>=2.2.2",
  "tqdm==4.66.4",
  "typer==0.12.3",
  "platformdirs==4.2.2",
  "tabulate==0.9.0",
  "ollama==0.3.0",
  "mypy==1.11.0",
  "openpyxl==3.1.5",
  "openai>=1.78.0",
  "pandas-stubs>=2.2.3.250308",
]

[project.urls]
Homepage = "https://github.com/fajril/esdc"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
esdc = ["data/*"]

[tool.setuptools.exclude-package-data]
esdc = ["tests"]

[project.scripts]
esdc = "esdc:app"

