-- Drop the table if it already exists
DROP TABLE IF EXISTS project_timeseries;

CREATE TABLE IF NOT EXISTS project_timeseries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    report_date TEXT,
    report_year INTEGER,
    is_offshore INTEGER,
    basin86_id TEXT,
    basin128 TEXT, -- Basin name in 128 format
    province TEXT,
    operator_group TEXT,
    report_status TEXT,
    wk_id TEXT,
    wk_name TEXT,
    wk_area REAL, -- new column added
    wk_regionisasi_ngi TEXT, -- new column added
    wk_area_perwakilan_skkmigas TEXT, -- new column added
    psc_eff_start TEXT,
    psc_eff_end TEXT,
    wk_lat TEXT,
    wk_long TEXT,
    field_lat TEXT,
    field_long TEXT,
    wk_subgroup TEXT,
    operator_name TEXT,
    field_id TEXT,
    field_name TEXT,
    project_id TEXT,
    project_name TEXT,
    project_isactive INTEGER, -- new column added
    project_remarks TEXT, -- new column added
    vol_remarks TEXT, -- new column added
    frcast_remarks TEXT, -- new column added
    pod_letter_num TEXT, -- new column added
    pod_name TEXT, -- new column added
    onstream_year INTEGER,
    onstream_actual TEXT,
    project_class TEXT,
    project_level TEXT,
    -- production_stage TEXT,
    prod_stage TEXT, -- new column added. Duplicate with production_stage
    year INTEGER, --new column added. Duplicate with frcast_year
    hist_year INTEGER,
    -- frcast_year INTEGER,
    cprd_grs_oil REAL,
    cprd_grs_con REAL,
    cprd_grs_ga REAL,
    cprd_grs_gn REAL,
    cprd_grs_oc REAL,
    cprd_grs_an REAL,
    cprd_sls_oil REAL,
    cprd_sls_con REAL,
    cprd_sls_ga REAL,
    cprd_sls_gn REAL,
    cprd_sls_oc REAL,
    cprd_sls_an REAL,
    rate_oil REAL,
    rate_con REAL,
    rate_ga REAL,
    rate_gn REAL,
    rate_oc REAL,
    rate_an REAL,
    tpf_oil REAL,
    tpf_con REAL,
    tpf_ga REAL,
    tpf_gn REAL,
    tpf_oc REAL,
    tpf_an REAL,
    tpf_risked_oil REAL,
    tpf_risked_con REAL,
    tpf_risked_ga REAL,
    tpf_risked_gn REAL,
    tpf_risked_oc REAL,
    tpf_risked_an REAL,
    slf_oil REAL,
    slf_con REAL,
    slf_ga REAL,
    slf_gn REAL,
    slf_oc REAL,
    slf_an REAL,
    spf_oil REAL,
    spf_con REAL,
    spf_ga REAL,
    spf_gn REAL,
    spf_oc REAL,
    spf_an REAL,
    crf_oil REAL,
    crf_con REAL,
    crf_ga REAL,
    crf_gn REAL,
    crf_oc REAL,
    crf_an REAL,
    prf_oil REAL,
    prf_con REAL,
    prf_ga REAL,
    prf_gn REAL,
    prf_oc REAL,
    prf_an REAL,
    ciof_oil REAL,
    ciof_con REAL,
    ciof_ga REAL,
    ciof_gn REAL,
    ciof_oc REAL,
    ciof_an REAL,
    lossf_oil REAL,
    lossf_con REAL,
    lossf_ga REAL,
    lossf_gn REAL,
    lossf_oc REAL,
    lossf_an REAL,
    ghv REAL
);