from dataclasses import dataclass


@dataclass
class ColumnMetadata:
    column_name: str
    description: str
    units: str | None = None
    category: str | None = None
    volume_type: str | None = None
    substance: str | None = None
    requires_classification: bool = False  # True for rec_* columns


COLUMN_GROUPS: dict[str, list[str]] = {
    "reserves": ["res_oil", "res_con", "res_ga", "res_gn", "res_oc", "res_an"],
    "resources": [
        "rec_oil",
        "rec_con",
        "rec_ga",
        "rec_gn",
        "rec_oc",
        "rec_an",
        "rec_mboe",
    ],
    "resources_risked": [
        "rec_oil_risked",
        "rec_con_risked",
        "rec_ga_risked",
        "rec_gn_risked",
        "rec_oc_risked",
        "rec_an_risked",
        "rec_mboe_risked",
    ],
    "eur_reserves": [
        "eur_res_oil",
        "eur_res_con",
        "eur_res_ga",
        "eur_res_gn",
        "eur_res_oc",
        "eur_res_an",
    ],
    "eur_resources": [
        "eur_rec_oil",
        "eur_rec_con",
        "eur_rec_ga",
        "eur_rec_gn",
        "eur_rec_oc",
        "eur_rec_an",
    ],
    "in_place": ["prj_ioip", "prj_igip"],
    "recovery_factors": [
        "rf_oil",
        "rf_gas",
        "urf_rec_oil",
        "urf_rec_gas",
        "urf_res_oil",
        "urf_res_gas",
    ],
    "production_rates": [
        "rate_grs_oil",
        "rate_grs_con",
        "rate_grs_ga",
        "rate_grs_gn",
        "rate_grs_oc",
        "rate_grs_an",
        "rate_sls_oil",
        "rate_sls_con",
        "rate_sls_ga",
        "rate_sls_gn",
        "rate_sls_oc",
        "rate_sls_an",
    ],
    "cumulative_production": [
        "cprd_grs_oil",
        "cprd_grs_con",
        "cprd_grs_ga",
        "cprd_grs_gn",
        "cprd_grs_oc",
        "cprd_grs_an",
        "cprd_sls_oil",
        "cprd_sls_con",
        "cprd_sls_ga",
        "cprd_sls_gn",
        "cprd_sls_oc",
        "cprd_sls_an",
    ],
    "discrepancy": [
        "dcpy_um_oil",
        "dcpy_um_con",
        "dcpy_um_ga",
        "dcpy_um_gn",
        "dcpy_um_oc",
        "dcpy_um_an",
        "dcpy_ppa_oil",
        "dcpy_ppa_con",
        "dcpy_ppa_ga",
        "dcpy_ppa_gn",
        "dcpy_ppa_oc",
        "dcpy_ppa_an",
        "dcpy_wi_oil",
        "dcpy_wi_con",
        "dcpy_wi_ga",
        "dcpy_wi_gn",
        "dcpy_wi_oc",
        "dcpy_wi_an",
        "dcpy_cio_oil",
        "dcpy_cio_con",
        "dcpy_cio_ga",
        "dcpy_cio_gn",
        "dcpy_cio_oc",
        "dcpy_cio_an",
        "dcpy_gtr_oil",
        "dcpy_gtr_con",
        "dcpy_gtr_ga",
        "dcpy_gtr_gn",
        "dcpy_gtr_oc",
        "dcpy_gtr_an",
        "dcpy_uc_oil",
        "dcpy_uc_con",
        "dcpy_uc_ga",
        "dcpy_uc_gn",
        "dcpy_uc_oc",
        "dcpy_uc_an",
    ],
    "identification": [
        "id",
        "uuid",
        "project_id",
        "project_name",
        "project_name_previous",
        "field_id",
        "field_name",
        "field_name_previous",
        "wk_id",
        "wk_name",
        "operator_name",
        "operator_group",
    ],
    "location": [
        "province",
        "prov_id",
        "basin86",
        "basin86_id",
        "basin128",
        "basin128_id",
        "wk_lat",
        "wk_long",
        "wk_area",
        "wk_area_ori",
        "wk_area_latest",
        "field_lat",
        "field_long",
        "is_offshore",
    ],
    "contract": [
        "psc_eff_start",
        "psc_eff_end",
        "wk_subgroup",
        "wk_area_perwakilan_skkmigas",
        "wk_regionisasi_ngi",
        "pod_letter_num",
        "pod_name",
        "pod_date",
    ],
    "classification": [
        "project_stage",
        "project_class",
        "project_level",
        "project_level_previous",
        "uncert_level",
        "prod_stage",
        "project_eol",
        "project_isactive",
        "is_discovered",
        "is_ltp",
        "is_pse_approved",
        "is_pod_approved",
        "is_report_accepted",
        "is_unitization",
        "onstream_year",
        "onstream_actual",
    ],
    "report_metadata": [
        "report_date",
        "report_year",
        "report_status",
        "project_remarks",
        "vol_remarks",
    ],
    "other": [
        "pd",
        "ghv_avg",
        "gcf_srock",
        "gcf_res",
        "gcf_ts",
        "gcf_dyn",
        "gcf_total",
        "groovy_isactive",
        "fusion_isactive",
    ],
    # Timeseries forecast columns
    "timeseries_forecast_tpf": [
        "tpf_oil",
        "tpf_con",
        "tpf_ga",
        "tpf_gn",
        "tpf_oc",
        "tpf_an",
    ],
    "timeseries_forecast_tpf_risked": [
        "tpf_risked_oil",
        "tpf_risked_con",
        "tpf_risked_ga",
        "tpf_risked_gn",
        "tpf_risked_oc",
        "tpf_risked_an",
    ],
    "timeseries_forecast_slf": [
        "slf_oil",
        "slf_con",
        "slf_ga",
        "slf_gn",
        "slf_oc",
        "slf_an",
    ],
    "timeseries_forecast_spf": [
        "spf_oil",
        "spf_con",
        "spf_ga",
        "spf_gn",
        "spf_oc",
        "spf_an",
    ],
    "timeseries_forecast_crf": [
        "crf_oil",
        "crf_con",
        "crf_ga",
        "crf_gn",
        "crf_oc",
        "crf_an",
    ],
    "timeseries_forecast_prf": [
        "prf_oil",
        "prf_con",
        "prf_ga",
        "prf_gn",
        "prf_oc",
        "prf_an",
    ],
    "timeseries_forecast_ciof": [
        "ciof_oil",
        "ciof_con",
        "ciof_ga",
        "ciof_gn",
        "ciof_oc",
        "ciof_an",
    ],
    "timeseries_forecast_lossf": [
        "lossf_oil",
        "lossf_con",
        "lossf_ga",
        "lossf_gn",
        "lossf_oc",
        "lossf_an",
    ],
    "timeseries_historical_cumulative": [
        "cprd_grs_oil",
        "cprd_grs_con",
        "cprd_grs_ga",
        "cprd_grs_gn",
        "cprd_grs_oc",
        "cprd_grs_an",
        "cprd_sls_oil",
        "cprd_sls_con",
        "cprd_sls_ga",
        "cprd_sls_gn",
        "cprd_sls_oc",
        "cprd_sls_an",
    ],
    "timeseries_historical_rate": [
        "rate_oil",
        "rate_con",
        "rate_ga",
        "rate_gn",
        "rate_oc",
        "rate_an",
    ],
}


COLUMN_METADATA: dict[str, ColumnMetadata] = {
    # Identification
    "id": ColumnMetadata("id", "Primary key (auto-increment)", None, "identification"),
    "uuid": ColumnMetadata(
        "uuid", "Unique identifier (UUID v4)", None, "identification"
    ),
    "project_id": ColumnMetadata(
        "project_id", "Project identifier from ESDC", None, "identification"
    ),
    "project_name": ColumnMetadata(
        "project_name", "Name of the project", None, "identification"
    ),
    "field_name": ColumnMetadata(
        "field_name", "Name of the field", None, "identification"
    ),
    "wk_name": ColumnMetadata("wk_name", "Work area name", None, "identification"),
    "operator_name": ColumnMetadata(
        "operator_name", "Operator company name", None, "identification"
    ),
    # Location
    "province": ColumnMetadata("province", "Province name", None, "location"),
    "basin128": ColumnMetadata(
        "basin128", "Basin name (128 classification)", None, "location"
    ),
    "is_offshore": ColumnMetadata(
        "is_offshore", "Whether location is offshore (0/1)", None, "location"
    ),
    # Classification
    "project_class": ColumnMetadata(
        "project_class",
        "Project classification (Reserves & GRR, Contingent Resources, Prospective Resources)",
        None,
        "classification",
    ),
    "uncert_level": ColumnMetadata(
        "uncert_level",
        "Uncertainty level (1. Low Value, 2. Middle Value, 3. High Value)",
        None,
        "classification",
    ),
    "project_level": ColumnMetadata(
        "project_level", "Project maturity level", None, "classification"
    ),
    "report_year": ColumnMetadata(
        "report_year", "Report year", None, "report_metadata"
    ),
    # Reserves columns
    "res_oil": ColumnMetadata(
        "res_oil", "Reserves oil", "MSTB", "reserves", "reserves", "oil"
    ),
    "res_con": ColumnMetadata(
        "res_con", "Reserves condensate", "MSTB", "reserves", "reserves", "condensate"
    ),
    "res_ga": ColumnMetadata(
        "res_ga",
        "Reserves associated gas",
        "BSCF",
        "reserves",
        "reserves",
        "associated_gas",
    ),
    "res_gn": ColumnMetadata(
        "res_gn",
        "Reserves non-associated gas",
        "BSCF",
        "reserves",
        "reserves",
        "non_associated_gas",
    ),
    "res_oc": ColumnMetadata(
        "res_oc",
        "Reserves oil + condensate",
        "MSTB",
        "reserves",
        "reserves",
        "oil_condensate",
    ),
    "res_an": ColumnMetadata(
        "res_an",
        "Reserves total gas (associated + non-associated)",
        "BSCF",
        "reserves",
        "reserves",
        "total_gas",
    ),
    # Resources columns
    "rec_oil": ColumnMetadata(
        "rec_oil", "Resources oil", "MSTB", "resources", "resources", "oil"
    ),
    "rec_con": ColumnMetadata(
        "rec_con",
        "Resources condensate",
        "MSTB",
        "resources",
        "resources",
        "condensate",
    ),
    "rec_ga": ColumnMetadata(
        "rec_ga",
        "Resources associated gas",
        "BSCF",
        "resources",
        "resources",
        "associated_gas",
    ),
    "rec_gn": ColumnMetadata(
        "rec_gn",
        "Resources non-associated gas",
        "BSCF",
        "resources",
        "resources",
        "non_associated_gas",
    ),
    "rec_oc": ColumnMetadata(
        "rec_oc",
        "Resources oil + condensate",
        "MSTB",
        "resources",
        "resources",
        "oil_condensate",
    ),
    "rec_an": ColumnMetadata(
        "rec_an", "Resources total gas", "BSCF", "resources", "resources", "total_gas"
    ),
    "rec_mboe": ColumnMetadata(
        "rec_mboe", "Resources (MBOE)", "MBOE", "resources", "resources", None
    ),
    # Risked Resources columns
    "rec_oil_risked": ColumnMetadata(
        "rec_oil_risked",
        "Risked Resources oil",
        "MSTB",
        "resources_risked",
        "resources",
        "oil",
    ),
    "rec_con_risked": ColumnMetadata(
        "rec_con_risked",
        "Risked Resources condensate",
        "MSTB",
        "resources_risked",
        "resources",
        "condensate",
    ),
    "rec_ga_risked": ColumnMetadata(
        "rec_ga_risked",
        "Risked Resources associated gas",
        "BSCF",
        "resources_risked",
        "resources",
        "associated_gas",
    ),
    "rec_gn_risked": ColumnMetadata(
        "rec_gn_risked",
        "Risked Resources non-associated gas",
        "BSCF",
        "resources_risked",
        "resources",
        "non_associated_gas",
    ),
    "rec_oc_risked": ColumnMetadata(
        "rec_oc_risked",
        "Risked Resources oil + condensate",
        "MSTB",
        "resources_risked",
        "resources",
        "oil_condensate",
    ),
    "rec_an_risked": ColumnMetadata(
        "rec_an_risked",
        "Risked Resources gas",
        "BSCF",
        "resources_risked",
        "resources",
        "total_gas",
    ),
    # In-Place columns
    "prj_ioip": ColumnMetadata(
        "prj_ioip", "Initial Oil In Place", "MSTB", "in_place", "inplace", "oil"
    ),
    "prj_igip": ColumnMetadata(
        "prj_igip", "Initial Gas In Place", "BSCF", "in_place", "inplace", "total_gas"
    ),
    # EUR columns
    "eur_res_oc": ColumnMetadata(
        "eur_res_oc",
        "EUR Reserves oil + condensate",
        "MSTB",
        "eur_reserves",
        "eur",
        "oil_condensate",
    ),
    "eur_res_an": ColumnMetadata(
        "eur_res_an", "EUR Reserves gas", "BSCF", "eur_reserves", "eur", "total_gas"
    ),
    "eur_rec_oc": ColumnMetadata(
        "eur_rec_oc",
        "EUR Resources oil + condensate",
        "MSTB",
        "eur_resources",
        "eur",
        "oil_condensate",
    ),
    "eur_rec_an": ColumnMetadata(
        "eur_rec_an", "EUR Resources gas", "BSCF", "eur_resources", "eur", "total_gas"
    ),
    # Recovery Factors
    "rf_oil": ColumnMetadata(
        "rf_oil", "Recovery factor oil", "fraction", "recovery_factors", None, "oil"
    ),
    "rf_gas": ColumnMetadata(
        "rf_gas",
        "Recovery factor gas",
        "fraction",
        "recovery_factors",
        None,
        "total_gas",
    ),
    # Production Rates
    "rate_grs_oc": ColumnMetadata(
        "rate_grs_oc",
        "Gross production rate oil + condensate",
        "MSTBY",
        "production_rates",
        "rate",
        "oil_condensate",
    ),
    "rate_grs_an": ColumnMetadata(
        "rate_grs_an",
        "Gross production rate gas",
        "BSCFY",
        "production_rates",
        "rate",
        "total_gas",
    ),
    # Timeseries Forecast Columns - TPF (Total Potential Forecast)
    "tpf_oil": ColumnMetadata(
        "tpf_oil",
        "Total Potential Forecast oil",
        "MSTB",
        "timeseries_forecast_tpf",
        "forecast",
        "oil",
    ),
    "tpf_con": ColumnMetadata(
        "tpf_con",
        "Total Potential Forecast condensate",
        "MSTB",
        "timeseries_forecast_tpf",
        "forecast",
        "condensate",
    ),
    "tpf_ga": ColumnMetadata(
        "tpf_ga",
        "Total Potential Forecast associated gas",
        "BSCF",
        "timeseries_forecast_tpf",
        "forecast",
        "associated_gas",
    ),
    "tpf_gn": ColumnMetadata(
        "tpf_gn",
        "Total Potential Forecast non-associated gas",
        "BSCF",
        "timeseries_forecast_tpf",
        "forecast",
        "non_associated_gas",
    ),
    "tpf_oc": ColumnMetadata(
        "tpf_oc",
        "Total Potential Forecast oil + condensate",
        "MSTB",
        "timeseries_forecast_tpf",
        "forecast",
        "oil_condensate",
    ),
    "tpf_an": ColumnMetadata(
        "tpf_an",
        "Total Potential Forecast total gas",
        "BSCF",
        "timeseries_forecast_tpf",
        "forecast",
        "total_gas",
    ),
    "tpf_risked_oil": ColumnMetadata(
        "tpf_risked_oil",
        "Risked Forecast oil",
        "MSTB",
        "timeseries_forecast_tpf_risked",
        "forecast",
        "oil",
    ),
    "tpf_risked_con": ColumnMetadata(
        "tpf_risked_con",
        "Risked Forecast condensate",
        "MSTB",
        "timeseries_forecast_tpf_risked",
        "forecast",
        "condensate",
    ),
    "tpf_risked_ga": ColumnMetadata(
        "tpf_risked_ga",
        "Risked Forecast associated gas",
        "BSCF",
        "timeseries_forecast_tpf_risked",
        "forecast",
        "associated_gas",
    ),
    "tpf_risked_gn": ColumnMetadata(
        "tpf_risked_gn",
        "Risked Forecast non-associated gas",
        "BSCF",
        "timeseries_forecast_tpf_risked",
        "forecast",
        "non_associated_gas",
    ),
    "tpf_risked_oc": ColumnMetadata(
        "tpf_risked_oc",
        "Risked Forecast oil + condensate",
        "MSTB",
        "timeseries_forecast_tpf_risked",
        "forecast",
        "oil_condensate",
    ),
    "tpf_risked_an": ColumnMetadata(
        "tpf_risked_an",
        "Risked Forecast total gas",
        "BSCF",
        "timeseries_forecast_tpf_risked",
        "forecast",
        "total_gas",
    ),
    # Timeseries Forecast Columns - SLF (Sales Forecast)
    "slf_oil": ColumnMetadata(
        "slf_oil",
        "Sales Forecast oil",
        "MSTB",
        "timeseries_forecast_slf",
        "forecast",
        "oil",
    ),
    "slf_con": ColumnMetadata(
        "slf_con",
        "Sales Forecast condensate",
        "MSTB",
        "timeseries_forecast_slf",
        "forecast",
        "condensate",
    ),
    "slf_ga": ColumnMetadata(
        "slf_ga",
        "Sales Forecast associated gas",
        "BSCF",
        "timeseries_forecast_slf",
        "forecast",
        "associated_gas",
    ),
    "slf_gn": ColumnMetadata(
        "slf_gn",
        "Sales Forecast non-associated gas",
        "BSCF",
        "timeseries_forecast_slf",
        "forecast",
        "non_associated_gas",
    ),
    "slf_oc": ColumnMetadata(
        "slf_oc",
        "Sales Forecast oil + condensate",
        "MSTB",
        "timeseries_forecast_slf",
        "forecast",
        "oil_condensate",
    ),
    "slf_an": ColumnMetadata(
        "slf_an",
        "Sales Forecast total gas",
        "BSCF",
        "timeseries_forecast_slf",
        "forecast",
        "total_gas",
    ),
    # Timeseries Forecast Columns - SPF (Sales Potential Forecast)
    "spf_oil": ColumnMetadata(
        "spf_oil",
        "Sales Potential Forecast oil",
        "MSTB",
        "timeseries_forecast_spf",
        "forecast",
        "oil",
    ),
    "spf_con": ColumnMetadata(
        "spf_con",
        "Sales Potential Forecast condensate",
        "MSTB",
        "timeseries_forecast_spf",
        "forecast",
        "condensate",
    ),
    "spf_ga": ColumnMetadata(
        "spf_ga",
        "Sales Potential Forecast associated gas",
        "BSCF",
        "timeseries_forecast_spf",
        "forecast",
        "associated_gas",
    ),
    "spf_gn": ColumnMetadata(
        "spf_gn",
        "Sales Potential Forecast non-associated gas",
        "BSCF",
        "timeseries_forecast_spf",
        "forecast",
        "non_associated_gas",
    ),
    "spf_oc": ColumnMetadata(
        "spf_oc",
        "Sales Potential Forecast oil + condensate",
        "MSTB",
        "timeseries_forecast_spf",
        "forecast",
        "oil_condensate",
    ),
    "spf_an": ColumnMetadata(
        "spf_an",
        "Sales Potential Forecast total gas",
        "BSCF",
        "timeseries_forecast_spf",
        "forecast",
        "total_gas",
    ),
    # Timeseries Forecast Columns - CRF (Contingent Resources Forecast)
    "crf_oil": ColumnMetadata(
        "crf_oil",
        "Contingent Resources Forecast oil",
        "MSTB",
        "timeseries_forecast_crf",
        "forecast",
        "oil",
    ),
    "crf_con": ColumnMetadata(
        "crf_con",
        "Contingent Resources Forecast condensate",
        "MSTB",
        "timeseries_forecast_crf",
        "forecast",
        "condensate",
    ),
    "crf_ga": ColumnMetadata(
        "crf_ga",
        "Contingent Resources Forecast associated gas",
        "BSCF",
        "timeseries_forecast_crf",
        "forecast",
        "associated_gas",
    ),
    "crf_gn": ColumnMetadata(
        "crf_gn",
        "Contingent Resources Forecast non-associated gas",
        "BSCF",
        "timeseries_forecast_crf",
        "forecast",
        "non_associated_gas",
    ),
    "crf_oc": ColumnMetadata(
        "crf_oc",
        "Contingent Resources Forecast oil + condensate",
        "MSTB",
        "timeseries_forecast_crf",
        "forecast",
        "oil_condensate",
    ),
    "crf_an": ColumnMetadata(
        "crf_an",
        "Contingent Resources Forecast total gas",
        "BSCF",
        "timeseries_forecast_crf",
        "forecast",
        "total_gas",
    ),
    # Timeseries Forecast Columns - PRF (Prospective Resources Forecast)
    "prf_oil": ColumnMetadata(
        "prf_oil",
        "Prospective Resources Forecast oil",
        "MSTB",
        "timeseries_forecast_prf",
        "forecast",
        "oil",
    ),
    "prf_con": ColumnMetadata(
        "prf_con",
        "Prospective Resources Forecast condensate",
        "MSTB",
        "timeseries_forecast_prf",
        "forecast",
        "condensate",
    ),
    "prf_ga": ColumnMetadata(
        "prf_ga",
        "Prospective Resources Forecast associated gas",
        "BSCF",
        "timeseries_forecast_prf",
        "forecast",
        "associated_gas",
    ),
    "prf_gn": ColumnMetadata(
        "prf_gn",
        "Prospective Resources Forecast non-associated gas",
        "BSCF",
        "timeseries_forecast_prf",
        "forecast",
        "non_associated_gas",
    ),
    "prf_oc": ColumnMetadata(
        "prf_oc",
        "Prospective Resources Forecast oil + condensate",
        "MSTB",
        "timeseries_forecast_prf",
        "forecast",
        "oil_condensate",
    ),
    "prf_an": ColumnMetadata(
        "prf_an",
        "Prospective Resources Forecast total gas",
        "BSCF",
        "timeseries_forecast_prf",
        "forecast",
        "total_gas",
    ),
    # Timeseries Forecast Columns - CIOF (Consumed in Operation Forecast)
    "ciof_oil": ColumnMetadata(
        "ciof_oil",
        "Consumed in Operation Forecast oil",
        "MSTB",
        "timeseries_forecast_ciof",
        "forecast",
        "oil",
    ),
    "ciof_con": ColumnMetadata(
        "ciof_con",
        "Consumed in Operation Forecast condensate",
        "MSTB",
        "timeseries_forecast_ciof",
        "forecast",
        "condensate",
    ),
    "ciof_ga": ColumnMetadata(
        "ciof_ga",
        "Consumed in Operation Forecast associated gas",
        "BSCF",
        "timeseries_forecast_ciof",
        "forecast",
        "associated_gas",
    ),
    "ciof_gn": ColumnMetadata(
        "ciof_gn",
        "Consumed in Operation Forecast non-associated gas",
        "BSCF",
        "timeseries_forecast_ciof",
        "forecast",
        "non_associated_gas",
    ),
    "ciof_oc": ColumnMetadata(
        "ciof_oc",
        "Consumed in Operation Forecast oil + condensate",
        "MSTB",
        "timeseries_forecast_ciof",
        "forecast",
        "oil_condensate",
    ),
    "ciof_an": ColumnMetadata(
        "ciof_an",
        "Consumed in Operation Forecast total gas",
        "BSCF",
        "timeseries_forecast_ciof",
        "forecast",
        "total_gas",
    ),
    # Timeseries Forecast Columns - LOSSF (Loss Production Forecast)
    "lossf_oil": ColumnMetadata(
        "lossf_oil",
        "Loss Production Forecast oil",
        "MSTB",
        "timeseries_forecast_lossf",
        "forecast",
        "oil",
    ),
    "lossf_con": ColumnMetadata(
        "lossf_con",
        "Loss Production Forecast condensate",
        "MSTB",
        "timeseries_forecast_lossf",
        "forecast",
        "condensate",
    ),
    "lossf_ga": ColumnMetadata(
        "lossf_ga",
        "Loss Production Forecast associated gas",
        "BSCF",
        "timeseries_forecast_lossf",
        "forecast",
        "associated_gas",
    ),
    "lossf_gn": ColumnMetadata(
        "lossf_gn",
        "Loss Production Forecast non-associated gas",
        "BSCF",
        "timeseries_forecast_lossf",
        "forecast",
        "non_associated_gas",
    ),
    "lossf_oc": ColumnMetadata(
        "lossf_oc",
        "Loss Production Forecast oil + condensate",
        "MSTB",
        "timeseries_forecast_lossf",
        "forecast",
        "oil_condensate",
    ),
    "lossf_an": ColumnMetadata(
        "lossf_an",
        "Loss Production Forecast total gas",
        "BSCF",
        "timeseries_forecast_lossf",
        "forecast",
        "total_gas",
    ),
    # Timeseries Historical Columns - Cumulative Production
    "cprd_grs_oil": ColumnMetadata(
        "cprd_grs_oil",
        "Cumulative gross production oil",
        "MSTB",
        "timeseries_historical_cumulative",
        "cumulative",
        "oil",
    ),
    "cprd_grs_con": ColumnMetadata(
        "cprd_grs_con",
        "Cumulative gross production condensate",
        "MSTB",
        "timeseries_historical_cumulative",
        "cumulative",
        "condensate",
    ),
    "cprd_grs_ga": ColumnMetadata(
        "cprd_grs_ga",
        "Cumulative gross production associated gas",
        "BSCF",
        "timeseries_historical_cumulative",
        "cumulative",
        "associated_gas",
    ),
    "cprd_grs_gn": ColumnMetadata(
        "cprd_grs_gn",
        "Cumulative gross production non-associated gas",
        "BSCF",
        "timeseries_historical_cumulative",
        "cumulative",
        "non_associated_gas",
    ),
    "cprd_grs_oc": ColumnMetadata(
        "cprd_grs_oc",
        "Cumulative gross production oil + condensate",
        "MSTB",
        "timeseries_historical_cumulative",
        "cumulative",
        "oil_condensate",
    ),
    "cprd_grs_an": ColumnMetadata(
        "cprd_grs_an",
        "Cumulative gross production total gas",
        "BSCF",
        "timeseries_historical_cumulative",
        "cumulative",
        "total_gas",
    ),
    "cprd_sls_oil": ColumnMetadata(
        "cprd_sls_oil",
        "Cumulative sales oil",
        "MSTB",
        "timeseries_historical_cumulative",
        "cumulative",
        "oil",
    ),
    "cprd_sls_con": ColumnMetadata(
        "cprd_sls_con",
        "Cumulative sales condensate",
        "MSTB",
        "timeseries_historical_cumulative",
        "cumulative",
        "condensate",
    ),
    "cprd_sls_ga": ColumnMetadata(
        "cprd_sls_ga",
        "Cumulative sales associated gas",
        "BSCF",
        "timeseries_historical_cumulative",
        "cumulative",
        "associated_gas",
    ),
    "cprd_sls_gn": ColumnMetadata(
        "cprd_sls_gn",
        "Cumulative sales non-associated gas",
        "BSCF",
        "timeseries_historical_cumulative",
        "cumulative",
        "non_associated_gas",
    ),
    "cprd_sls_oc": ColumnMetadata(
        "cprd_sls_oc",
        "Cumulative sales oil + condensate",
        "MSTB",
        "timeseries_historical_cumulative",
        "cumulative",
        "oil_condensate",
    ),
    "cprd_sls_an": ColumnMetadata(
        "cprd_sls_an",
        "Cumulative sales total gas",
        "BSCF",
        "timeseries_historical_cumulative",
        "cumulative",
        "total_gas",
    ),
    # Timeseries Historical Columns - Production Rate
    "rate_oil": ColumnMetadata(
        "rate_oil",
        "Production rate oil",
        "MSTB/Y",
        "timeseries_historical_rate",
        "rate",
        "oil",
    ),
    "rate_con": ColumnMetadata(
        "rate_con",
        "Production rate condensate",
        "MSTB/Y",
        "timeseries_historical_rate",
        "rate",
        "condensate",
    ),
    "rate_ga": ColumnMetadata(
        "rate_ga",
        "Production rate associated gas",
        "BSCF/Y",
        "timeseries_historical_rate",
        "rate",
        "associated_gas",
    ),
    "rate_gn": ColumnMetadata(
        "rate_gn",
        "Production rate non-associated gas",
        "BSCF/Y",
        "timeseries_historical_rate",
        "rate",
        "non_associated_gas",
    ),
    "rate_oc": ColumnMetadata(
        "rate_oc",
        "Production rate oil + condensate",
        "MSTB/Y",
        "timeseries_historical_rate",
        "rate",
        "oil_condensate",
    ),
    "rate_an": ColumnMetadata(
        "rate_an",
        "Production rate total gas",
        "BSCF/Y",
        "timeseries_historical_rate",
        "rate",
        "total_gas",
    ),
}


def get_column_group(column_name: str) -> str | None:
    """
    Get the group name for a column.

    Args:
        column_name: Name of the column

    Returns:
        Group name or None if not found
    """
    for group_name, columns in COLUMN_GROUPS.items():
        if column_name in columns:
            return group_name

        for col in columns:
            if col.endswith("*"):
                prefix = col[:-1]
                if column_name.startswith(prefix):
                    return group_name
    return None
