"""Synonym mappings for Indonesian/English terminology."""

from typing import Dict

SYNONYMS: Dict[str, str] = {
    "cadangan": "cadangan",
    "reserves": "cadangan",
    "reserve": "cadangan",
    "sumber daya": "sumber_daya",
    "resources": "sumber_daya",
    "resource": "sumber_daya",
    "sumberdaya": "sumber_daya",
    "terbukti": "proven",
    "proven": "proven",
    "mungkin": "probable",
    "probable": "probable",
    "harapan": "possible",
    "possible": "possible",
    "1p": "1P",
    "2p": "2P",
    "3p": "3P",
    "1r": "1R",
    "2r": "2R",
    "3r": "3R",
    "1c": "1C",
    "2c": "2C",
    "3c": "3C",
    "1u": "1U",
    "2u": "2U",
    "3u": "3U",
    "grr": "grr",
    "government recoverable": "grr",
    "contingent": "contingent",
    "kontijen": "contingent",
    "prospective": "prospective",
    "prospek": "prospective",
    "lapangan": "field",
    "field": "field",
    "wilayah kerja": "wk",
    "wk": "wk",
    "work area": "wk",
    # Forecast types synonyms
    "tpf": "tpf",
    "total potential forecast": "tpf",
    "slf": "slf",
    "sales forecast": "slf",
    "sales lift": "slf",
    "spf": "spf",
    "sales potential forecast": "spf",
    "sales profile": "spf",
    "crf": "crf",
    "contingent resources forecast": "crf",
    "prf": "prf",
    "prospective resources forecast": "prf",
    "ciof": "ciof",
    "consumed in operation forecast": "ciof",
    "lossf": "lossf",
    "loss production forecast": "lossf",
    "operator": "operator",
    "basin": "basin",
    "cekungan": "basin",
    "provinsi": "province",
    "province": "province",
    "minyak": "oil",
    "oil": "oil",
    "kondensat": "condensate",
    "condensate": "condensate",
    "gas": "total_gas",
    "inplace": "inplace",
    "in-place": "inplace",
    "in place": "inplace",
    "igip": "inplace",
    "ioip": "inplace",
    "eur": "eur",
    "estimated ultimate recovery": "eur",
    "recovery factor": "recovery_factor",
    "rf": "recovery_factor",
    "produksi": "production",
    "production": "production",
    # Timeseries synonyms
    "perkiraan": "forecast",
    "forecast": "forecast",
    "proyeksi": "forecast",
    "projection": "forecast",
    "produksi kedepan": "forecast",
    "future production": "forecast",
    "ramalan": "forecast",
    "puncak produksi": "peak_production",
    "peak production": "peak_production",
    "produksi maksimum": "peak_production",
    "maximum production": "peak_production",
    "plateau": "plateau",
    "mendatar": "plateau",
    "produksi stabil": "plateau",
    "stable production": "plateau",
    "decline": "decline",
    "penurunan": "decline",
    "produksi menurun": "decline",
    "falling production": "decline",
    "ramp up": "ramp_up",
    "peningkatan": "ramp_up",
    "naik produksi": "ramp_up",
    "increasing production": "ramp_up",
    "end of life": "eol",
    "eol": "eol",
    "masa akhir produksi": "eol",
    "last production year": "eol",
    "tahun akhir produksi": "eol",
    "onstream": "onstream",
    "on stream": "onstream",
    "mulai produksi": "onstream",
    "start production": "onstream",
    "tahun onstream": "onstream",
    "shut in": "shut_in",
    "penutupan sumur": "shut_in",
    "well shut": "shut_in",
    "timeseries": "timeseries",
    "time series": "timeseries",
    "time-series": "timeseries",
    "profil produksi": "timeseries",
    "production profile": "timeseries",
}
